name: SailfishOS build

on:
  push:
    branches:
      - master
      - harbour
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 4.4.0.68

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ['armv7hl', 'aarch64', 'i486']

    steps:
    - uses: actions/checkout@v5

    - name: Build ${{ matrix.arch }}
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE }}
        arch: ${{ matrix.arch }}

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms-${{ matrix.arch }}
        path: RPMS
